name: Lint and Deploy docs to GitHub pages.

on:
  # Run on push to master
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Check job
  check:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust installation
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Restore cache Maelstrom Binary
        id: restore-maelstrom
        uses: actions/cache/restore@v3
        with:
          path: maelstrom
          key: maelstrom
      - name: Download maelstrom
        if: steps.restore-maelstrom.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/jepsen-io/maelstrom/releases/download/v0.2.3/maelstrom.tar.bz2
          tar -xjf maelstrom.tar.bz2
          rm maelstrom.tar.bz2
      - name: Cache Maelstrom Binary
        uses: actions/cache@v3
        with:
          path: maelstrom
          key: maelstrom
      - name: Install GNU plot
        run: sudo apt update && sudo apt install gnuplot
      - name: Test
        run: cargo test --all-features
      - name: Test Challenges
        env:
          MAELSTROM_BIN: ./maelstrom/maelstrom
        run: cargo test -p xtask
      - name: Format
        uses: actions-rust-lang/rustfmt@v1
      - name: Lint
        run: cargo clippy --all-targets --all-features --locked -- -D warnings

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rust installation
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Generate Docs
        run: cargo doc --no-deps
      - name: Generate 404 html
        # ref: https://github.com/rust-lang/rust/issues/73185
        run: |
          cat > target/doc/404.html << EOF
          <script>
          window.onload = function() {
            window.location.href = "${{ github.event.repository.name }}"
          }
          </script>
          EOF
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc/

  # Deployment document
  deploy_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
